### ISSUE TITLE
About KL divergence in CVAE

### ISSUE THREAD

**Issue by sinlin0908** [valdersoul/bn-vae#4]
Thank you for your released code.  
I have a question about the computation of KL divergence in CVAE. 
In the paper, the KL term in the new bound is the sum of  KL(qφ(z|x, y) || pθ(z|x)) and  KL(pθ(z|x)||r(z)).

Does it mean  ![](http://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{i=1}^{n}{(\mu_{pi}^{2}+\sigma_{pi}^{2}-\log{\sigma_{pi}^{2}}-1)+(\log{\sigma_{pi}^{2}}-\log{\sigma_{qi}^{2}}-1+\frac{\sigma_{qi}^{2}+(\mu_{qi}-\mu_{pi})^{2}}{\sigma_{pi}^{2}})})  ?

I get   ![](http://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{i=1}^{n}{\frac{\sigma_{qi}^{2}+(\mu_{qi}-\mu_{pi})^{2}}{\sigma_{pi}^{2}}+\mu_{pi}^{2}+\sigma_{pi}^{2}-\log{\sigma_{qi}^{2}}-2}), which is different from paper.

The result in the paper is ![](http://latex.codecogs.com/gif.latex?\frac{1}{2}\sum_{i=1}^{n}{\frac{\sigma_{qi}^{2}+(\mu_{qi}-\mu_{pi})^{2}}{\sigma_{pi}^{2}}+\mu_{pi}^{2}+\sigma_{pi}^{2}-\log{\sigma_{qi}^{2}}-1}).

Does the constant term 2 or 1 have any effect?

**Comment by valdersoul** [comment]
Hi, thanks for pointing out the mistake here and sorry for the late reply.

Does the constant term 2 or 1 have any effect?

I thinkt it won't since when do the partial derivation would ignore the constant anyway (in the appendix).

**Comment by sinlin0908** [comment]
For my options, theoretically, if constant term is 1, one of KL divergence functions would not be correct.

**Comment by valdersoul** [comment]
Yes, it would be wrong. So I double check the code for cvae (a littler messy so not release sorry about it), it's right as below. Sorry for the typo and misunderstanding.
 
![image](https://user-images.githubusercontent.com/4101276/101854023-a2122580-3b9b-11eb-88cf-21d2f1288b92.png)

**Comment by sinlin0908** [comment]
In my code, according to my equation,  the way I compute the KL divergence in CVAE is different from yours as below.
```Python
def compute_KL_divergence(recog_mu, recog_logvar, prior_mu, prior_logvar):
    kld = 0.5 * torch.sum(-2 + torch.exp(prior_logvar) + torch.pow(prior_mu, 2)-recog_logvar
                          + torch.div(torch.pow(recog_mu-prior_mu,
                                                2), torch.exp(prior_logvar))
                          + torch.div(torch.exp(recog_logvar), torch.exp(prior_logvar)), 1)
    return kld
```
I don't know whether my code is wrong.
thank you.

**Comment by valdersoul** [comment]
You are right in the code. Mine is only the gaussian kld, and I do it seperately.

**Comment by sinlin0908** [comment]
appreciate it.
